# todo
# Gradi_PRIVATE_FRAMEWORKS = CoverSheet PlatterKit SpringBoard MediaRemote FrontBoard

# DEBUG = 1

OS = 14.5
ARCH = arm64

APP_NAME = @@PROJECTNAME@@
FILES = src/*.swift

include $(DIYCOMPILE)/diycompile.mk
