# todo
# Gradi_PRIVATE_FRAMEWORKS = CoverSheet PlatterKit SpringBoard MediaRemote FrontBoard

# OS = 14.5
# ARCH = arm64
# DEBUG = 1

APP_NAME = @@PROJECTNAME@@
FILES = *.swift

include $(DIYCOMPILE)/diycompile.mk
