CLIENT = @@CLIENT@@
INSTALL_PATH = /Applications

OS = @@OS@@
ARCH = @@ARCH@@

SWIFP_NAME = @@PROJECTNAME@@

FILES = src/*.swift
RESOURCES = Resources/*

ENTITLEMENTS = entitlements.plist

GIMME_PERM = 1

include $(DIYCOMPILE)/diycompile.mk
