CLIENT = @@CLIENT@@
INSTALL_PATH = /usr/local/bin

OS = @@OS@@
ARCH = @@ARCH@@

RUST_NAME = @@PROJECTNAME@@
RESOURCES = Resources/*

ENTITLEMENTS = entitlements.plist

INFO = Info.plist
GIMME_PERM = 1

include $(DIYCOMPILE)/diycompile.mk
