CLIENT = @@CLIENT@@
INSTALL_PATH = /Applications

OS = @@OS@@
ARCH = @@ARCH@@

RUSP_NAME = @@PROJECTNAME@@
RESOURCES = Resources/*

ENTITLEMENTS = entitlements.plist

GIMME_PERM = 1

include $(DIYCOMPILE)/diycompile.mk
