# OS = 14.5
# ARCH = arm64
# DEBUG = 1

# CODESIGN_FLAGS = -Sentitlements.plist
# INSTALL_PATH = /usr/local/bin

TOOL_NAME = @@PROJECTNAME@@

FILES = *.swift
ENTITLEMENTS = entitlements.plist

include $(DIYCOMPILE)/diycompile.mk