# DEBUG = 1

# CODESIGN_FLAGS = -Sentitlements.plist
# INSTALL_PATH = /usr/local/bin

OS = 14.5
ARCH = arm64

SWIFT_NAME = @@PROJECTNAME@@

FILES = src/*.swift
ENTITLEMENTS = entitlements.plist

include $(DIYCOMPILE)/diycompile.mk