CLIENT = @@CLIENT@@
INSTALL_PATH = /usr/local/bin

OS = @@OS@@
ARCH = @@ARCH@@

SWIFT_NAME = @@PROJECTNAME@@
FILES = src/*.swift

ENTITLEMENTS = entitlements.plist
INFO = Info.plist

GIMME_PERM = 1

include $(DIYCOMPILE)/diycompile.mk